# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0002_auto_20170227_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(choices=[('D', 'Donation'), ('E', 'Earning')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('timestamp', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('current_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('achievements', models.ManyToManyField(to='rewards_app.Achievement')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='rewards_app.User')),
            ],
        ),
        migrations.RenameField(
            model_name='charity',
            old_name='mission_statement',
            new_name='description',
        ),
        migrations.AddField(
            model_name='charity',
            name='image_url',
            field=models.URLField(default='http://google.com'),
        ),
        migrations.AddField(
            model_name='charity',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charity',
            name='website',
            field=models.URLField(default='http://google.com'),
        ),
        migrations.AddField(
            model_name='activity',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards_app.Charity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards_app.User'),
        ),
    ]
