# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0003_auto_20170318_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='charity',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
