# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards_app', '0004_auto_20170325_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('current_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('achievements', models.ManyToManyField(blank=True, to='rewards_app.Achievement')),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='rewards_app.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards_app.Profile'),
        ),
    ]
