# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0004_auto_20170325_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='rewards_app.Achievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='rewards_app.User'),
        ),
    ]
