# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0005_auto_20170405_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards_app.Charity'),
        ),
    ]
